insert into library values(100,'Pre-K Read-Aloud Stories');
insert into library values(101,'English Fairy Tales,');
insert into library values(102,'Library Lion');
insert into library values(103,'Not so quite library');


insert into book (id,lib_id,title,author,publisher,rating,content) 
values (201,100,'The Ant And The Grasshopper','Arthur Rackham',' Favorite Fairy Tales',5,
'One bright day in late autumn a family of Ants were bustling about in the warm sunshine, drying out the grain they had stored up during the summer, when a starving Grasshopper, his fiddle under his arm, came up and humbly begged for a bite to eat."What!" cried the Ants in surprise, "haven''t you stored anything away for the winter? What in the world were you doing all last summer?""I didn''t have time to store up any food," whined the Grasshopper; "I was so busy making music that before I knew it the summer was gone."The Ants shrugged their shoulders in disgust."Making music, were you?" they cried. "Very well; now dance!" And they turned their backs on the Grasshopper and went on with their work.There''s a time for work and a time for play.');

insert into book (id,lib_id,title,author,publisher,rating,content) 
values (202,100,'The Three Little Pigs','Arthur Rackham',' Favorite Fairy Tales',4,
'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.The first little pig was very lazy. He didn''t want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.The third little pig worked hard all day and built his house with bricks. It was a sturdy house complete with a fine fireplace and chimney. It looked like it could withstand the strongest winds.The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the strau house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.So he knocked on the door and said:');

insert into book (id,lib_id,title,author,publisher,rating,content) 
values (203,100,'The Bogey-Beast','Arthur Rackham',' Favorite Fairy Tales',3,
'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.The first little pig was very lazy. He didn''t want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.The third little pig worked hard all day and built his house with bricks. It was a sturdy house complete with a fine fireplace and chimney. It looked like it could withstand the strongest winds.The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the strau house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.So he knocked on the door and said:');


insert into book (id,lib_id,title,author,publisher,rating,content) 
values (204,101,'The Snow Queen','Arthur Rackham',' Favorite Fairy Tales',5,
'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.The first little pig was very lazy. He didn''t want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.The third little pig worked hard all day and built his house with bricks. It was a sturdy house complete with a fine fireplace and chimney. It looked like it could withstand the strongest winds.The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the strau house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.So he knocked on the door and said:');


insert into book (id,lib_id,title,author,publisher,rating,content) 
values (205,101,'The Father Frost','Arthur Rackham',' Favorite Fairy Tales',2,
'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.The first little pig was very lazy. He didn''t want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.The third little pig worked hard all day and built his house with bricks. It was a sturdy house complete with a fine fireplace and chimney. It looked like it could withstand the strongest winds.The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the strau house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.So he knocked on the door and said:');

insert into book (id,lib_id,title,author,publisher,rating,content) 
values (206,101,'The Bogey-Beast','Arthur Rackham',' Favorite Fairy Tales',1,
'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.The first little pig was very lazy. He didn''t want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.The third little pig worked hard all day and built his house with bricks. It was a sturdy house complete with a fine fireplace and chimney. It looked like it could withstand the strongest winds.The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the strau house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.So he knocked on the door and said:');


insert into book (id,lib_id,title,author,publisher,rating,content) 
values (207,102,'Snow white','Arthur Rackham',' Favorite Fairy Tales',5,
'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.The first little pig was very lazy. He didn''t want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.The third little pig worked hard all day and built his house with bricks. It was a sturdy house complete with a fine fireplace and chimney. It looked like it could withstand the strongest winds.The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the strau house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.So he knocked on the door and said:');


insert into book (id,lib_id,title,author,publisher,rating,content) 
values (208,102,'The Litle Thief in Pantry','Arthur Rackham',' Favorite Fairy Tales',3,
'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.The first little pig was very lazy. He didn''t want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.The third little pig worked hard all day and built his house with bricks. It was a sturdy house complete with a fine fireplace and chimney. It looked like it could withstand the strongest winds.The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the strau house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.So he knocked on the door and said:');

insert into book (id,lib_id,title,author,publisher,rating,content) 
values (209,102,'The Tale of Peter Robbit','Arthur Rackham',' Favorite Fairy Tales',4,
'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.The first little pig was very lazy. He didn''t want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.The third little pig worked hard all day and built his house with bricks. It was a sturdy house complete with a fine fireplace and chimney. It looked like it could withstand the strongest winds.The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the strau house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.So he knocked on the door and said:');


